### ISSUE TITLE
Why does this project use react-icons?

### ISSUE THREAD

**Issue by the-serious-programmer** [sjdemartini/mui-tiptap#119]
Wanted to use this package, but seeing react-icons being added as an extra dependency to my project is a bummer. Would love if there is an option to only use the mui icons that are already available in every mui project.

**Comment by bryanjtc** [comment]
Shifting react-icons to the project dependencies is indeed a step in the right direction. However, I'd like to highlight that even after installation and unpacking, the package still appears to be quite substantial, at 77.7mb. Given that only a handful of icons are being utilized, it might be more efficient to incorporate those specific icons directly into the bundle.

**Comment by sjdemartini** [comment]
@bryanjtc Thanks for chiming in! Including the SVG icons directly in the project makes `mui-tiptap` development a bit less convenient (e.g. if we need to include another icon, it won't be as simple as an import), but I think that may be a cost worth paying to reduce the dependencies and installation/download size. I'll explore this and follow up.

**Comment by sjdemartini** [comment]
Alright, the latest release [v1.3.0](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.3.0) removes the `react-icons` peer dependency and defines these additional icons internally within `mui-tiptap` instead. Thanks again @the-serious-programmer and @bryanjtc for bringing this up and discussing!
