### ISSUE TITLE
When draggable is enabled and text select at the edge of the sentence  , it lose selection.

### ISSUE THREAD

**Issue by v3ss0n** [sjdemartini/mui-tiptap#145]
### Describe the bug

When `draggable` is enabled on non-inline items , and  text is selected , the selection is lost - randomly .

### To Reproduce

Please include a CodeSandbox demo of the problem if possible. (You can fork [this CodeSandbox](https://codesandbox.io/p/sandbox/mui-tiptap-demo-3zl2l6).)

1. Enable draggble
2. Try to select Text , starting at the right most position.
3. Text selection will be resetted.

### Expected behavior

Text selectable

### System (please complete the following information):

- mui-tiptap version: [e.g. 1.7.3]
- tiptap version: [e.g. 2.0.1]
- Browser: [e.g. Chrome - latest]
- Node version: [e.g 16.4.2]
- OS: [e.g. Ubuntu 22.04, macOS 11.4]

**Comment by sjdemartini** [comment]
@v3ss0n I don't follow the repro steps. For which extensions are you enabling `draggable: true``? `ResizableImage` is for instance a non-inline item which has `draggable: true`, and text selection works fine for me, as in the default CodeSandbox. Would you be able to provide a CodeSandbox by forking the one linked above? Could you also provide your mui-tiptap version, tiptap version, etc as requested in the issue template? My guess is that what you're trying to accomplish may actually be an issue in Tiptap itself, not related to mui-tiptap, so I would suggest filing there if so.

**Comment by v3ss0n** [comment]
We are now able to solve thitby adding a wrapper block component for dragging. Thanks alot.

**Comment by sjdemartini** [comment]
Okay, glad you found a way to make it work!
