### ISSUE TITLE
Instilation failure

### ISSUE THREAD

**Issue by alectoparty** [sjdemartini/mui-tiptap#151]
Fails to install with the following error: 

preinstall: `npx only-allow pnpm`

ReadMe say use "npm install mui-tiptap" 

Any way this can be installed via npm?

**Comment by sjdemartini** [comment]
@alectoparty Did you end up figuring out the issue? I believe `only-allow` should only affect local development within `mui-tiptap` not installation outside of mui-tiptap. e.g. the CodeSandbox demo is using `yarn` successfully. I haven't tried npm but can double-check if for some reason it has an issue installing mui-tiptap.
