### ISSUE TITLE
Change Remaining @mui/icons-material imports to Direct Path Imports

### ISSUE THREAD

**Issue by cwierzbicki00** [sjdemartini/mui-tiptap#154]
### Describe the bug

On some platforms, such as Nextjs 13, an issue emerges due to the large bundle size of mui-tiptap / it's import method for some of "@mui/icons-material".  For most of the codebase, direct path imports are used. There are some areas where the tree shaking imports are used, which bloat the package and are strangely linked to issues on Nextjs 13.

### To Reproduce

Not possible to reproduce without a full Nextjs 13 deployment on Vercel. Not necessarily relevant, either.

1. Deploy any NextJS13 application to Vercel which uses API features.
2. Attempt to call the API by some page action.
3. Receive 504 timeout errors, like discussed in (https://github.com/vercel/next.js/discussions/47237) 

### Expected behavior

The inclusion of mui-tiptap should safely import the icons from @mui/icons-material using the direct path. Then, the application runs smoothly.

### Screenshots

Simply need to change from 
![image](https://github.com/sjdemartini/mui-tiptap/assets/29385924/60c65493-6f42-46f3-bc04-fd82f816b050)
to this
![image](https://github.com/sjdemartini/mui-tiptap/assets/29385924/9f97c9b5-e8e1-4495-b925-fe3502bcd663)

### System (please complete the following information):

- mui-tiptap version: 1.8.2
- tiptap version: ^2.0.0
- Browser: Chrome
- Node version: 18.17.1
- OS: Windows 11

### Additional context

 Regardless, this will reduce the bundle size and is considered best practice. (See mui docs https://mui.com/material-ui/icons/#usage )
 
The imports should be changed to direct path imports unless the techniques specified here are used https://mui.com/material-ui/guides/minimizing-bundle-size/#option-two-use-a-babel-plugin 
 
It is my first time contributing on OSS, so please forgive any mishaps. I am a really big fan of this project and am impressed with the design & codebase. I will attempt to open a PR for this issue shortly.

**Comment by sjdemartini** [comment]
Thank you for reporting and detailing this @cwierzbicki00! This is something that had been on my radar vaguely but I hadn't pursued making changes yet. I suppose per https://mui.com/material-ui/guides/minimizing-bundle-size/#when-and-how-to-use-tree-shaking, we should be updating not just the `@mui/icons-material` paths but also the `@mui/material` component paths as well. Those can definitely be done separately though. I'll take at your PR shortly, thanks again!

**Comment by sjdemartini** [comment]
Resolved via https://github.com/sjdemartini/mui-tiptap/pull/155, and now enforcing with an eslint rule via https://github.com/sjdemartini/mui-tiptap/pull/159.

And as mentioned in https://github.com/sjdemartini/mui-tiptap/pull/155#issuecomment-1721534645, we'll stick with the top-level named imports still for `@mui/material`, since the issue doesn't seem to arise there and it's a better development experience.
