### ISSUE TITLE
Question: How does mui-tiptap maintain text selection when controls are clicked

### ISSUE THREAD

**Issue by csandman** [sjdemartini/mui-tiptap#164]
Hey, sorry this isn't a feature request but I couldn't figure out the best way to ask a question!

I haven't actually been using it, but this package is great! I've been working on my own implementation of TipTap for Chakra UI, and this package has provided a lot of useful examples of how to make custom extensions and properly type some of the examples they have in the original demos.

The one thing I have not been able to figure out though, is how you manage to maintain the text selection inside the editor when other elements are focused. In my case specifically, I'm trying to prevent a selected block of text from unselecting as soon as I click on the font selector dropdown. I've found some hacky ways to do it by re-selecting the current selection after the dropdown opens, but it prevents my dropdown from being interactable (using my [chakra wrapper for react select](https://github.com/csandman/chakra-react-select)). I'd be very grateful if you could provide any info on how you managed to accomplish this, even if that's just to point me somewhere in this repo where you handle that.

Hopefully this isn't me just doing something stupid haha.

**Comment by csandman** [comment]
Actually, not that I'm looking at it, I think this might be an issue with react-select specifically breaking the default selection behavior and have nothing to do with something specific you did. I'm going to close this, sorry

**Comment by sjdemartini** [comment]
@csandman glad mui-tiptap has been useful as a reference! No worries about opening the issue, and glad you found the underlying cause. Like you suggested, I don't believe I'm doing anything special. In general, my approach is to just `focus()` the editor again once the action is complete. e.g. for font size, it calls `focus()` on change of the value:

https://github.com/sjdemartini/mui-tiptap/blob/82271b8e2a66cba742762fda1cdb80f7414130c2/src/controls/MenuSelectFontSize.tsx#L196-L203

I think a primary reason this "works" and doesn't show the selected editor text as deselected is MUI's use of a popover for the Select UI, where there is no focus on the actual options or interaction with them until the user clicks one to select (at which point `onChange` is called and it then calls `focus()` again anyway). I believe when I tried to use MUI's `Autocomplete` component (https://mui.com/material-ui/react-autocomplete/, which is seemingly more similar to your chakra react-select dropdown), I ran into a similar inconvenient UX problem as you, where the user's caret changed focus to the Autocomplete element and therefore the browser removed the visual text selection in the editor. If you happen to find a good workaround, I'd be interested to hear it!

**Comment by csandman** [comment]
Thanks for getting back! Yeah I believe that was the main issue, that react select is primarily a combobox (autocomplete) so it pulls in focus to it's input. There is an option to disable the search part, but it still drew focus. My solution was honestly just to use a different component haha.
