### ISSUE TITLE
Module not found: Can't resolve '@mui/icons-material/Checklist'

### ISSUE THREAD

**Issue by mydoooom** [sjdemartini/mui-tiptap#166]
<img width="599" alt="Screenshot 2023-10-03 at 17 28 43" src="https://github.com/sjdemartini/mui-tiptap/assets/19497537/5cd7782c-70fc-45a6-a8ae-dc4176426901">

I'm trying to use mui-tiptap in my Next.js project but got this error during build time. I've got @mui/material version 5.14.11, @mui/icons-material is at 5.11.11. When can find the CheckList icon on [their docs](https://mui.com/material-ui/material-icons), but cannot import it in my project.

**Comment by sjdemartini** [comment]
No worries, glad it's working now that that peer dependency package is installed! Thanks for following up after you resolved it
