### ISSUE TITLE
Unindent button icon is wrong 

### ISSUE THREAD

**Issue by mydoooom** [sjdemartini/mui-tiptap#168]
<img width="380" alt="Screenshot 2023-10-08 at 15 21 54" src="https://github.com/sjdemartini/mui-tiptap/assets/19497537/aa9ee72a-3d1c-4648-806c-3babcc99606f">

Here on the repo on `src/controls/MenuButtonUnindent.tsx`, the button import is correct, but when I checked  my project's `node_modules` in `node_modules/mui-tiptap/dist/controls/MenuButtonUnindent.js`, there's 
`const FormatIndentIncrease_1 = __importDefault(require("@mui/icons-material/FormatIndentIncrease"));` on line 7

**Comment by sjdemartini** [comment]
Thanks for reporting! It looks like the name for the default import is correct, but it's not referencing the right path anymore https://github.com/sjdemartini/mui-tiptap/blob/82271b8e2a66cba742762fda1cdb80f7414130c2/src/controls/MenuButtonUnindent.tsx#L1 as of a change in v1.8.3. I won't be able to get to a computer for a little bit, but I'll fix and release once I'm able! In the meantime you can downgrade to 1.8.2.

**Comment by sjdemartini** [comment]
This is fixed in the newly published [1.8.4](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.8.4). Thanks again for reporting!

**Comment by mydoooom** [comment]
Awesome, thank you!
