### ISSUE TITLE
Color Picker not working with shadow dom

### ISSUE THREAD

**Issue by simon-schuster44** [sjdemartini/mui-tiptap#176]
### Describe the bug

Everything was working fine so far, because useRef is used for the components. But the color picker buttton works with event.currentTarget, which isn't accessible in the shadow dom. Any idea how i can solve that?

### To Reproduce

` <MenuButton
        onClick={(e) =>
          anchorEl ? handleClose() : setAnchorEl(e.currentTarget)
        }
        aria-describedby={popperId}
        {...otherMenuButtonProps}
      >`

1. When implementing MenuButtonTextColor or MenuButtonHighlightColor in shadow dom, the color picker wont appear

### System (please complete the following information):

- mui-tiptap version: 1.8.5
- tiptap version:  2.1.12
- Browser: Chrome
- Node version: 16.4.2
- OS: win11

**Comment by sjdemartini** [comment]
@simon-schuster44 as mentioned in https://github.com/sjdemartini/mui-tiptap/issues/177#issuecomment-1791300215, I'm not very familiar with shadow dom usage with React components. Would you be able to provide a CodeSandbox example that illustrates the problem?

**Comment by simon-schuster44** [comment]
Update: The MuiPopper comes with a z-Index of three, which let him hide behind my page. I set it to 999 and now everything works fine. It was always there, I'm kinda ashamed now :D

**Comment by sjdemartini** [comment]
@simon-schuster44 Great, glad you were able to figure it out! Thanks for following up and closing the issue
