### ISSUE TITLE
CSS classes mangled in production build

### ISSUE THREAD

**Issue by bartlangelaan** [sjdemartini/mui-tiptap#178]
### Describe the bug

During development, all CSS classes are nicely available. For example, `MuiTiptap-RichTextField-content` can be found in the DOM. This is nice, because we can override some styles using CSS this way.

However, in a production build the CSS properties are minified. Now, `MuiTiptap-Xy-content` can be found in the DOM. This is probabily because the function names are minified, and the function names are used to generate the CSS classes.

### To Reproduce

To reproduce, you can open the default demo (https://codesandbox.io/p/sandbox/mui-tiptap-demo-3zl2l6) and in the terminal, use the `build` step. Then, open the 'preview' URL (change port 5173 to 4173). The CSS classes are now different.

### Expected behavior

I would expect the CSS classes to be the same in a development build, and in a production build.

### System (please complete the following information):

- mui-tiptap version: v1.8.5

### Additional context

Probabily, the use of `function.name` needs to be avoided, because the function name is minified in most production builds.
See: https://github.com/sjdemartini/mui-tiptap/blob/main/src/RichTextContent.tsx#L19C20-L19C20

Hard-coding the component name is, I think, the only option here. [MUI seems to do that aswell.](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Autocomplete/autocompleteClasses.ts#L65C13-L65C13)

**Comment by sjdemartini** [comment]
@bartlangelaan Great catch, thank you for reporting! You're probably right that hard-coding the name is the only option. Feel free to open a PR for that if you'd like, or otherwise I'll plan on getting to that soon.

**Comment by sjdemartini** [comment]
This should be fixed in [v1.8.6](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.8.6), just released. Thanks again for the very clear and helpful report!
