### ISSUE TITLE
How do I skip the `formatHref` behavior?

### ISSUE THREAD

**Issue by geekyayush** [sjdemartini/mui-tiptap#182]
### Is your feature request related to a problem? Please describe.
I found this function `formatHref` in file: `/src/LinkBubbleMenu/EditLinkMenuContent.tsx`

How can I remove or skip its behavior?
![image](https://github.com/sjdemartini/mui-tiptap/assets/25874080/4bdcbf92-055c-4048-bcc6-01045bb985ea)

**Comment by sjdemartini** [comment]
There is currently no built-in way to sidestep this behavior in mui-tiptap. I may add an option to override the `formatHref` function as a prop, so you can customize to whatever behavior you need, thanks for suggesting.

**Comment by geekyayush** [comment]
> There is currently no built-in way to sidestep this behavior in mui-tiptap. I may add an option to override the `formatHref` function as a prop, so you can customize to whatever behavior you need, thanks for suggesting.

It would be awesome if this can be added. thanks.

**Comment by sjdemartini** [comment]
Also open to PRs which add this, if you'd like to take a crack at it!

**Comment by sjdemartini** [comment]
This is now possible as of https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.13.0. You can customize the formatting with the new `formatHref` prop, or you can fully skip it like `<LinkBubbleMenu formatHref={(value) => value} />`.
