### ISSUE TITLE
ediotr.can(...).setColor is not a function

### ISSUE THREAD

**Issue by abrenner94** [sjdemartini/mui-tiptap#187]
Hi,

i have some problems when i try to use `MenuButtonTextColor` or `MenuButtonUnderline`.
I am getting the error
`Uncaugt TypeError: editor.can(...).setColor is not a function`

I have already set up a codesandsbox where you can see the error:

[Codesandbox Demo](https://codesandbox.io/p/devbox/mui-tiptap-demo-forked-946dl3?file=%2Fsrc%2FApp.tsx%3A17%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr50vgul0007356irn4jem09%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr50vgul0002356i6g7d631y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr50vgul0004356i0nxkr89w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr50vgul0006356ixyixt602%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr50vgul0002356i6g7d631y%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr50vguk0001356i3vxr2taw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr56dxm50029356iew71554t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr56ibnc0002356isgnjlfax%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A33%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A35%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr50vgul0002356i6g7d631y%2522%252C%2522activeTabId%2522%253A%2522clr56dxm50029356iew71554t%2522%257D%252C%2522clr50vgul0006356ixyixt602%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr50vgul0005356iyh5w7vyv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr50vgul0006356ixyixt602%2522%252C%2522activeTabId%2522%253A%2522clr50vgul0005356iyh5w7vyv%2522%257D%252C%2522clr50vgul0004356i0nxkr89w%2522%253A%257B%2522id%2522%253A%2522clr50vgul0004356i0nxkr89w%2522%252C%2522activeTabId%2522%253A%2522clr56lkzf0083356i4ksr8efe%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr50vgul0003356ivbb53ckm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clr56eewr00ap356idei130q4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr56ef0d01kbeeev6tvf67mh%2522%257D%252C%257B%2522id%2522%253A%2522clr56lkzf0083356i4ksr8efe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr56ll3h01kpeeevdy3l1lu9%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by sjdemartini** [comment]
@abrenner94 You need to install the Color extension and pass it in to the `editor`'s `extensions` array when you use `useEditor`. Please see https://github.com/sjdemartini/mui-tiptap/issues/174#issuecomment-1783299136

**Comment by muhannad-abbady** [comment]
'use client'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import ChooseBlock from './blocks'
import Script from 'next/script'
import '@/styles/jodit.min.css'
import { parseDimensions } from '@/helpers/public'
import ChooseWidget from './widgets'
import { useGlobalStore } from '@/stores/globalStore'
import Gallery from '../gallery'
import { Box, Button } from '@mui/material'
import AccessAlarmIcon from '@mui/icons-material/AccessAlarm'
import { useEditor } from "@tiptap/react"
import StarterKit from "@tiptap/starter-kit"
import {
    MenuButtonAddImage,
    MenuButtonBlockquote,
    MenuButtonBold,
    MenuButtonBulletedList,
    MenuButtonCode,
    MenuButtonHorizontalRule,
    MenuButtonIndent,
    MenuButtonItalic,
    MenuButtonOrderedList,
    MenuButtonRedo,
    MenuButtonSubscript,
    MenuButtonTextColor,
    MenuButtonUndo,
    MenuButtonUnindent,
    MenuControlsContainer,
    MenuDivider,
    MenuSelectFontFamily,
    MenuSelectFontSize,
    MenuSelectHeading,
    RichTextEditor,
    RichTextEditorProvider,
    RichTextField,
} from "mui-tiptap"

interface CmsEditorProps {
    placeholder?: string
    value: string
    id: string
    insertBlock?: boolean
    insertWidget?: boolean
    useCustomCss?: boolean // Handle custom CSS (compiled from .scss)
    onChange: ( newValue: string ) => void
    className?: string
}

declare global {
    interface Window {
        Jodit: any // Replace 'any' with the appropriate type if you have it
    }
}

const CmsEditor: React.FC<CmsEditorProps> = ( {
    placeholder,
    value,
    id,
    onChange,
    className,
    insertBlock = true,
    insertWidget = true,
    useCustomCss = true
} ) => {
    const [ scriptReady, setScriptReady ] = useState( false )
    const editorRef = useRef<any>()
    const openDrawer = useGlobalStore( state => state.mainDrawer )
    const closeDrawer = useGlobalStore( state => state.closeMainDrawer )
    const [ openBlock, setOpenBlock ] = useState( false )
    const [ openWidget, setOpenWidget ] = useState( false )
    const observer = useRef<MutationObserver | null>( null )
    const basePath = `${ process.env.NEXT_PUBLIC_ASSETS_URL }gallery`
    const editor = useEditor( {
        extensions: [ StarterKit ],
        content: "<p>Hello <b>world</b>!</p>",
    } )
    // const openGallery = () => {
    //     openDrawer( {
    //         props: {
    //             title: "Insert File...",
    //             onClose: () => {
    //                 closeDrawer()
    //             },
    //             sx: { ".body": { pt: 5, width: { sm: "88vw", md: "84vw", lg: "80vw", xl: "76vw" } } }
    //         },
    //         content: <Gallery onSelect={ ( img ) => {
    //             if ( img )
    //             {                    
    //                 var code =""
    //                 if ( img.type === "pdf" )
    //                 {
    //                     code = `<img src="${ basePath }${ img.path }/${ img!.small }" pdfSrc="${ basePath }${ img.path }/${ img!.fileName }" width="100%" height="auto">`
    //                 } else
    //                 {
    //                     code = `<img width="${ parseDimensions( img?.dimensions ).width }" height="${ parseDimensions( img?.dimensions ).height }" src="${ basePath }${ img.path }/${ img!.fileName }" alt="">`                        
    //                 }

    //                 closeDrawer()
    //                 setTimeout( () => editorRef.current.s?.insertHTML( code ), 100 )
    //             }
    //         } } onClose={ closeDrawer } />,
    //     } )
    // }

    // const buttons = [
    //     "undo", "redo", "|", "bold", "strikethrough", "underline", "italic", "|", "superscript", "subscript", "|", "align", "|", "ul", "ol", "outdent", "indent", "|", "font", "fontsize", "brush", "paragraph", "|", "image", "link", "table", "|", "hr", "eraser", "copyformat", "|", "fullsize", "selectall",
    //     ...( insertBlock ? [ "|", { name: 'Block', exec: ( editor: any ) => { setOpenBlock( true ); return true } }, "|" ] : [] ),
    //     ...( insertWidget ? [ "|", { name: 'Widget', exec: ( editor: any ) => { setOpenWidget( true ); return true } }, "|" ] : [] ),
    //     "|", { name: 'Gallery', exec: ( editor: any ) => { openGallery(); return true } }, "|", "source", "|",
    // ]

    // const config = useMemo( () => ( {
    //     enterBlock: "div",
    //     saveModeInStorage: false,
    //     defaultMode: 2,
    //     cleanHTML: { cleanOnPaste: false },
    //     readonly: false,
    //     placeholder: value ? "" : placeholder || 'Start typing...',
    //     toolbar: true,
    //     spellcheck: true,
    //     language: "en",
    //     autofocus: true,
    //     uploader: { insertImageAsBase64URI: true },
    //     height: 450,
    //     buttons: buttons,
    //     extraPlugins: [
    //         'customImagePlugin'
    //     ],
    // } ), [ placeholder, value ] );

    // useEffect( () => {
    //     if ( window?.Jodit && config )
    //     {
    //         editorRef.current = window?.Jodit?.make( "#" + id, config )
    //         editorRef.current.value = value // Set the initial value here
    //         editorRef.current.e?.on( 'change', ( newValue: string ) => {
    //             onChange( newValue )
    //         } )

    //         const editorDoc = editorRef.current?.editor?.ownerDocument
    //         if ( editorDoc )
    //         {               

    //             if ( useCustomCss )
    //             {
    //                 const tailwindStyleTag = document.createElement( 'link' )
    //                 tailwindStyleTag.rel = 'stylesheet'
    //                 tailwindStyleTag.href = 'https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css' // Use the latest or preferred version
    //                 editorDoc.head.appendChild( tailwindStyleTag )
    //             }

    //         }
    //     }
    // }, [ scriptReady, value, config, useCustomCss ] )


    return (
        value !== null ? (
            <>
                <RichTextEditor
                    ref={ editorRef }
                    extensions={ [ StarterKit ] } // Or any Tiptap extensions you wish!
                    content={ value } // Initial content for the editor
                    // Optionally include `renderControls` for a menu-bar atop the editor:
                    renderControls={ () => (
                        <MenuControlsContainer>
                            <MenuSelectHeading />
                            <MenuDivider />
                            <MenuButtonBold />
                            <MenuButtonItalic />
                            <MenuButtonBulletedList />
                            {/* <MenuButtonTextColor /> */}
                            <MenuButtonCode />
                            {/* <MenuSelectFontFamily options={ [ { label: "Monospace", value: "monospace" }] }/> */}
                            {/* <MenuSelectFontSize /> */}
                            <MenuButtonUndo />
                            <MenuButtonRedo />
                            <MenuButtonHorizontalRule />
                            {/* <MenuButtonAddImage onClick={ () => { } } /> */}
                            <MenuButtonIndent />
                            <MenuButtonUnindent />
                            <MenuButtonOrderedList />
                            {/* <MenuButtonSubscript /> */}

                        </MenuControlsContainer>
                    ) }
                />

                { insertBlock && (
                    <ChooseBlock open={ openBlock } onSelect={ ( value ) => {
                        setOpenBlock( false )
                        setTimeout( () => editorRef.current.s?.insertHTML( `{{widget type="cms-block" blockID="${ value }"}}` ), 50 )
                    } } onClose={ () => setOpenBlock( false ) } />
                ) }

                { insertWidget && (
                    <ChooseWidget open={ openWidget } onSelect={ ( widget: string, widgetType: string, component: string, params: string ) => {
                        setOpenWidget( false )
                        setTimeout( () => editorRef.current.s?.insertHTML(
                            widgetType !== "static"
                                ? `{{widget type="data-widget" widgetID="${ widget }" component="${ component }" params="${ params }"}}`
                                : `{{widget type="static" component="${ component }" params="${ params }"}}`
                        ), 50 )
                    } } onClose={ () => setOpenWidget( false ) } />
                ) }

            </>
        ) : null
    )
}

export default CmsEditor

i try ti use tiptap/react .. the code run as well
now i want to add a button to view a code mode

**Comment by muhannad-abbady** [comment]
how to addd button to change mode to html code edit ?
