### ISSUE TITLE
Set editor height to prevent dynamic height changes

### ISSUE THREAD

**Issue by woigl** [sjdemartini/mui-tiptap#198]
I want to set the editor height by lines or by pixels.

That means the initial editor without content already has a certain height, which should also stay the same with a lot of content. If required, scrollbars should appear.

Can that be achieved already, or does that require a code improvement?

**Comment by Shao-fract** [comment]
Hi, try something like  wrapping your RichTextField in a box and apply this :
`<Box
      ref={boxRef}
      sx={{
           "&& .ProseMirror": {
          height: "yourDesiredHeight",
          overflowY: "auto",
        },

      }}
    >
<YourRichTextField/>
</Box>
`

**Comment by sjdemartini** [comment]
CSS is indeed the approach I'd recommend, like in the snippet above. Closing out.

It may be worth making CSS overrides (in general) a bit easier for mui-tiptap at some point later, but for now the above is likely the simplest way to handle this use-case.
