### ISSUE TITLE
implement defaultValue for RichTextField

### ISSUE THREAD

**Issue by jshinroblox** [sjdemartini/mui-tiptap#200]
Find it hard to believe that there is no way to display a defaultValue in a RichTextField... if there is please tell me

**Comment by sjdemartini** [comment]
@jshinroblox You can set the `content` to whatever you want, and that will be used as the default value, as can be seen in the CodeSandbox linked from the README (https://codesandbox.io/p/devbox/mui-tiptap-demo-3zl2l6?file=%2Fsrc%2FEditor.tsx%3A142%2C1-143%2C1). This is the behavior of Tiptap's `useEditor` hook: https://tiptap.dev/docs/editor/api/editor#content

**Comment by jshinroblox** [comment]
> @jshinroblox You can set the `content` to whatever you want, and that will be used as the default value, as can be seen in the CodeSandbox linked from the README (https://codesandbox.io/p/devbox/mui-tiptap-demo-3zl2l6?file=%2Fsrc%2FEditor.tsx%3A142%2C1-143%2C1). This is the behavior of Tiptap's `useEditor` hook: https://tiptap.dev/docs/editor/api/editor#content

That is for a RichTextEditor. For a RichTextField there seems to be no way to do that.

**Comment by sjdemartini** [comment]
`RichTextField` renders the content that comes from the `editor`, so you should set `content` with the `useEditor` hook, which is what you then provide as context via `<RichTextEditorProvider editor={editor}>`. `RichTextField` is for displaying the content of the editor but does not update the editor's content, etc. itself.
