### ISSUE TITLE
MenuButtonIndent not working in TouchDevice or non-touch device

### ISSUE THREAD

**Issue by sfkaos** [sjdemartini/mui-tiptap#204]
### Describe the bug

With the `ListItem` extension installed I am unable to even click the MenuButtonIndent button.

I would like to use this button to easily create paragraphs.

### To Reproduce

Please include a CodeSandbox demo of the problem if possible. (You can fork [this CodeSandbox](https://codesandbox.io/p/sandbox/mui-tiptap-demo-3zl2l6).)

Scenario 1:
1. Start new line
2. Try clicking MenuButtonIndent button.

Scenario 2:
1. Highlight a line of text
2. Try clicking MenuButtonIndent button

### Expected behavior

I expect the MenuButtonIndent button to be clickable

### System (please complete the following information)

- mui-tiptap version: 1.8.6
- tiptap version: 2.2.4
- Browser: Chrome
- Node version: 18.17.0
- OS: Mac 14
- Copy-paste your `extensions` array used for the editor:

```
      TableImproved.configure({
        resizable: true,
      }),
      TableRow,
      TableHeader,
      TableCell,

      BulletList.configure({
        HTMLAttributes: {
          class: "ml-5",
        },
      }),
      CodeBlock,
      Document,
      HardBreak,
      ListItem,
      OrderedList.configure({
        HTMLAttributes: {
          class: "ml-5",
        },
      }),
      Paragraph.configure({
        HTMLAttributes: {
          class: "mb-2",
        },
      }),
      CustomSubscript,
      CustomSuperscript,
      Text,

      // Blockquote must come after Bold, since we want the "Cmd+B" shortcut to
      // have lower precedence than the Blockquote "Cmd+Shift+B" shortcut.
      // Otherwise using "Cmd+Shift+B" will mistakenly toggle the bold mark.
      // (See https://github.com/ueberdosis/tiptap/issues/4005,
      // https://github.com/ueberdosis/tiptap/issues/4006)
      Bold,
      Blockquote,

      Code,
      Italic,
      Underline,
      Strike,
      CustomLinkExtension.configure({
        // autolink is generally useful for changing text into links if they
        // appear to be URLs (like someone types in literally "example.com"),
        // though it comes with the caveat that if you then *remove* the link
        // from the text, and then add a space or newline directly after the
        // text, autolink will turn the text back into a link again. Not ideal,
        // but probably still overall worth having autolink enabled, and that's
        // how a lot of other tools behave as well.
        autolink: true,
        linkOnPaste: true,
        openOnClick: false,
      }),
      LinkBubbleMenuHandler,

      // Extensions
      Gapcursor,
      HeadingWithAnchor,
      TextAlign.configure({
        types: ["heading", "paragraph", "image"],
      }),
      TextStyle,
      Color,
      FontFamily,
      FontSize,
      Highlight.configure({ multicolor: true }),
      HorizontalRule,

      ResizableImage,
      // When images are dragged, we want to show the "drop cursor" for where they'll
      // land
      Dropcursor,

      TaskList,
      TaskItem.configure({
        nested: true,
      }),

      // Mention.configure({
      //   suggestion: mentionSuggestionOptions,
      // }),

      Placeholder.configure({
        placeholder,
      }),

      // We use the regular `History` (undo/redo) extension when not using
      // collaborative editing
      History,

```

**Comment by sjdemartini** [comment]
@sfkaos I'm afraid that's not what the "indent" functionality in Tiptap and the `MenuButtonIndent` button is for. The indent and unindent buttons are specifically for list items (bullet list, ordered/numbered list, and task item list), as seen here https://tiptap.dev/docs/editor/api/nodes/list-item with `sinkListItem` and `liftListItem`. They don't work to indent paragraphs of text.

Perhaps this third party package https://github.com/evanfuture/tiptaptop-extension-indent will accomplish what you want.

**Comment by sfkaos** [comment]
> @sfkaos I'm afraid that's not what the "indent" functionality in Tiptap and the `MenuButtonIndent` button is for. The indent and unindent buttons are specifically for list items (bullet list, ordered/numbered list, and task item list), as seen here https://tiptap.dev/docs/editor/api/nodes/list-item with `sinkListItem` and `liftListItem`. They don't work to indent paragraphs of text.
> 
> Perhaps this third party package https://github.com/evanfuture/tiptaptop-extension-indent will accomplish what you want.

Thank you so much for your prompt reply. Will look into that package ASAP!
