### ISSUE TITLE
`ref` failure in Nextjs project

### ISSUE THREAD

**Issue by kblizeck** [sjdemartini/mui-tiptap#207]
### Describe the bug

I am importing `mui-tiptap` dynamically into a Nextjs component. I am receiving a `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?` error.

### To Reproduce

Please include a CodeSandbox demo of the problem if possible.
[Code Sandbox](https://codesandbox.io/p/devbox/mui-tiptap-editor-npxsf8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clumxindc00073b6ia4j99mf5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clumxindc00023b6ifqr75qhc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clumxindc00043b6ip5xnbihm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clumxindc00063b6i4zm9q514%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clumxindc00023b6ifqr75qhc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumxindc00013b6idn2wwxor%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clumxindc00023b6ifqr75qhc%2522%252C%2522activeTabId%2522%253A%2522clumxindc00013b6idn2wwxor%2522%257D%252C%2522clumxindc00063b6i4zm9q514%2522%253A%257B%2522id%2522%253A%2522clumxindc00063b6i4zm9q514%2522%252C%2522activeTabId%2522%253A%2522clumxtgob011q3b6iofv6ld8y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumxindc00053b6idnobvz3o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clumxtgob011q3b6iofv6ld8y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clumxindc00043b6ip5xnbihm%2522%253A%257B%2522id%2522%253A%2522clumxindc00043b6ip5xnbihm%2522%252C%2522activeTabId%2522%253A%2522clumxrzqp00z63b6i7ftam0iu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clumxrzqp00z63b6i7ftam0iu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clumxrzx0000ndage9rwa2fgk%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. Install and dynamically load `mui-tiptap` in Nextjs project (app router)
2. Try to preset content in the editor
3. Console error about ref preventing content load.

### Expected behavior

Ref should be used in RichTextEditor as expected

### System (please complete the following information)

- mui-tiptap version: 1.8.6
- tiptap version: 2.2.2
- Browser: all
- Node version: 18.19.0
- OS: macOS 14.2.1
- Copy-paste your `extensions` array used for the editor:

```tsx
      BulletList,
      Document,
      ListItem,
      OrderedList,
      Paragraph,
      Text,
      Bold,
      Italic,
      Underline,
      HeadingWithAnchor,
      History,
```

**Comment by sjdemartini** [comment]
Thanks for including the CodeSandbox. I'm honestly not familiar enough with NextJS to debug this or understand the issue. 

I see you're using:

```tsx
const RichTextEditor = useMemo(
    () =>
      dynamic(
        import("mui-tiptap").then((module) => module.RichTextEditor),
        {
          ssr: false,
        },
      ),
    [],
  );
```

Their docs on lazy imports do seem to show a different pattern for external libraries than for internal code: https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-external-libraries (`await import()` rather than `dynamic(...)`). 

The docs on `dynamic()` also do say:

> `dynamic()` can't be used inside of React rendering as it needs to be marked in the top level of the module for preloading to work, similar to `React.lazy`.

So it seems to me that perhaps the import pattern you're using may not be valid. 🤔

**Comment by kblizeck** [comment]
@sjdemartini I tried moving the import but that didn't solve the issue - instead, I had to add another wrapper component that uses `forwardRef` to pass the ref to the `RichTextEditor` component. I updated the example here - https://codesandbox.io/p/devbox/mui-tiptap-editor-npxsf8?file=%2Fapp%2Fdocument.js

Thank you for taking a look! Going to close this issue out.
