### ISSUE TITLE
Bump TipTap deps to latest

### ISSUE THREAD

**Issue by vitality82** [sjdemartini/mui-tiptap#208]
### Is your feature request related to a problem? Please describe.

Curious what are the implications of upgrading underlying TipTap (and it's deps) to latest version (currently 2.2.6).

### Describe the solution you'd like

Authors insight; Did you already go down this path? Any gotchas to be aware?

**Comment by sjdemartini** [comment]
Yeah, the dependency range is intentionally lenient so that consuming apps can use older or newer versions of Tiptap. (I can bump dev dependencies used within mui-tiptap for its development, but the package should remain open to wider Tiptap version usage.)
