### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded.     at HTMLDocument.contain (FocusTrap.js:225:1)

### ISSUE THREAD

**Issue by perfectdeed** [sjdemartini/mui-tiptap#224]
Sorry, my boss don't pay me to fill bug report for you

Here the error I got: Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLDocument.contain (FocusTrap.js:225:1)
    
It happens when when I choose an option in any dropdown: MenuSelectFontFamily, MenuSelectHeading or MenuSelectFontSize.

Also, proper documentation would be appreciate.

Otherwise not a bad project.

Thank you.

**Comment by sjdemartini** [comment]
I don't have enough information to understand your setup, since the demo in the README works fine, as you can see for yourself. If you can provide more context, I may be able to investigate if it's a problem with mui-tiptap (and not Tiptap itself), but otherwise I will plan to close this out.

**Comment by perfectdeed** [comment]
surprinsigly
