### ISSUE TITLE
Module not found: Error: Can't resolve '@tiptap/starter-kit

### ISSUE THREAD

**Issue by brunoeacampos** [sjdemartini/mui-tiptap#230]
Sorry for my English.

I was try install, but one error was found. 
I tryed yarn add tiptap/starter-kit

console log.

thank you

yarn add tiptap/starter-kit
yarn add v1.22.22
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/tiptap/starter-kit.git
Directory: /home/bruno/app/sisPatriFront
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by sjdemartini** [comment]
You typed

```
yarn add tiptap/starter-kit
```

But it should be

```
yarn add @tiptap/starter-kit
```

This does not relate to mui-tiptap. Please direct any issues with TIptap itself to the Tiptap GitHub instead https://github.com/ueberdosis/tiptap
