### ISSUE TITLE
About TipTap

### ISSUE THREAD

**Issue by Broenfar** [sjdemartini/mui-tiptap#239]
First of all, I realize this is **_not the right place_** for such a question. The Discussions section isn't open, so I don't have anywhere else to ask.

Below I have listed TipTap's limitations on the free plan:

- Monthly connections (Every websocket session connecting to a document is counted as a connection.): **5K**
- Concurrent connections per app (The maximum number of websocket connections your Collaboration environment (e.g. app) can support at the same time.): **10**
- App pausing (For users on the Free plan, apps inactive for more than a week are paused, requiring manual reactivation.): **1 Week after inactivity**

( source: https://tiptap.dev/pricing )

Will these limits exist when using mui-tiptap?

_**I don't know if this is a stupid question, I really have no idea. So please be kind to me_

**Comment by sjdemartini** [comment]
@Broenfar mui-tiptap is really just a library that adds components for controls, extensions, and styling on top of Tiptap's rich text editor APIs (and uses Material UI styles). If you just install the standard Tiptap open-source libraries like in the CodeSandbox demo that is linked in the README, there are no limitations. You can do whatever you want with them.

Tiptap separately has a hosted version of its collaboration _server_, which you can pay for, which you can use to sync real-time collaboration content between different users. There's apparently a free tier for their hosted collaboration product which has the limitations you mentioned. These are specific to that product and don't relate to the editor open-source packages that are listed as peer dependencies in mui-tiptap and mentioned in the README, etc. You can also self-host a collaboration server if you do want real-time collaboration functionality (see https://tiptap.dev/docs/editor/collaboration/install, https://tiptap.dev/docs/editor/api/extensions/collaboration), and there are of course no such limitations then on number of connections (it'll be up to you to scale it, etc).
