### ISSUE TITLE
How to refine behavior?

### ISSUE THREAD

**Issue by antonio-bluco** [sjdemartini/mui-tiptap#244]
Hi, 

This is a great library, which I am enjoying for its ease of use! 

However, I am having some trouble understanding how to modify things when needed. 

I am facing two main issues: 
1. The bulleted list and numbered list are mutually exclusive. If I click the ordered list button (<MenuButtonOrderedList>) the Bullet list button (<MenuButtonBulletedList>) is greyed out and not available. I would like instead to simply be able to switch from one to the other, instead of having to go to normal, then go to the other. 
2. For some reason, I am getting no indentation by default on my lists, and they fall outside of the text editor. 

<img width="331" alt="Screenshot 2024-07-11 at 11 38 17" src="https://github.com/sjdemartini/mui-tiptap/assets/172268882/abcec15b-2800-4e71-a44d-9931ea46497b">

I am following pretty closely the official code [here](https://codesandbox.io/p/devbox/mui-tiptap-demo-3zl2l6?file=%2Fsrc%2FuseExtensions.ts%3A121%2C7-121%2C9),  but let's say that the main issue is that it's really hard to find any information online about how to modify the behavior of even why some things are happening. Which options / configuration do each component allow, etc . Perhaps I am looking in the wrong place? 

(A smaller, separate issue is that indentation does not seem to work - pressing tab just goes to another button on the page (i.e. it's not intercepted by the rich text editor) and the indent / unindent button seem to do nothing. However I care less about that and for now I simply disabled it). 

Would be grateful for any help!

**Comment by sjdemartini** [comment]
For (1), that sort of issue is directly from Tiptap functionality, not specific to mui-tiptap. (mui-tiptap's logic disables the menu button if Tiptap's API returns that the given command, in this case switching list type, is not allowed.) In general, as far as where to find information, I would recommend looking at Tiptap's documentation to know how Tiptap's extensions behave, how to modify Tiptap behavior when possible, etc. (for instance https://tiptap.dev/docs/editor/extensions/nodes/bullet-list). And also searching their Github for issues and discussions that pertain to your questions/issues (https://github.com/ueberdosis/tiptap/issues).

For (2), I'm not sure what your setup is, but the mui-tiptap default styles and demos do not have this issue. I'd recommend looking in your web inspector dev tools to see why the CSS is moving your list items. Perhaps you have some global CSS on your page that affect list items.

I'm going to close this out, but please let me know if there's something that you think is still an issue within mui-tiptap.
