### ISSUE TITLE
Update RichTextField with TipTap 2.5.x features?

### ISSUE THREAD

**Issue by t-monaco** [sjdemartini/mui-tiptap#249]
Is there path to upgrade TipTap to version 2.5.x and use `immediatelyRender` as a prop of `<RichTextEditor />`?

**Comment by sjdemartini** [comment]
Thanks for flagging this! You can start using those new options as of https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.9.4 😄

**Comment by t-monaco** [comment]
Thanks! 

Also, I think that the same should apply to `<RichTextReadOnly />`.

**Comment by sjdemartini** [comment]
> Thanks!
> 
> Also, I think that the same should apply to `<RichTextReadOnly />`.

Whoops, good catch, handled in https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.9.5
