### ISSUE TITLE
Hide tooltip (menu items) when opening dropdowns (e.g. font-size / paragraph)

### ISSUE THREAD

**Issue by alaa-paramount** [sjdemartini/mui-tiptap#308]
### Describe the bug

The tooltip menu items are currently displayed above all the drop-down selection menus which is disturbing for the user (sometimes it can block the selections from dropdown)

### To Reproduce

1. Hover over font-size menu (you will see tooltip of "Font size" by default)
2. When clicking and opening the dropdown of "font-size", you will keep seeing the tooltip of "Font size" above all the dropdown menu
3. The tooltip sometimes can block your dropdown selection (depends on dropdown position)

### Expected behavior

Menu tooltips should be hidden when user opening any drop-downs

**Comment by sjdemartini** [comment]
This is similar to https://github.com/sjdemartini/mui-tiptap/issues/282 and https://github.com/sjdemartini/mui-tiptap/issues/283, though slightly different/narrower issue and recommended solution. I do like the idea of closing the tooltip if you've opened select options, so I'll open a PR for that 😄

**Comment by sjdemartini** [comment]
This is now released in https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.15.1

**Comment by alaa-paramount** [comment]
@sjdemartini Works, thanks alot!
