### ISSUE TITLE
Add option to configure locale

### ISSUE THREAD

**Issue by bryanjtc** [sjdemartini/mui-tiptap#59]
### Is your feature request related to a problem? Please describe.

Mui has an option to configure the locale for their components using the global theme and importing the language tag from the locale package. The locale package exports named objects with the language tag that override the default props of the component and changes the language of the different texts that component has.
https://github.com/mui/material-ui/blob/master/packages/mui-material/src/locale/index.ts

### Describe the solution you'd like

Add a locale prop to each component or configure a global locale override. Simple components like Menu Buttons have only the label but bubble menus and other extensions have multiple labels and texts.

### Describe alternatives you've considered

Make each label/text prop of all extensions/controls customizable.

**Comment by sjdemartini** [comment]
Thanks again for reporting. I am intending to allow for customizing all of the labels/text, as you say! (as opposed to baking in the localized/translated content directly like MUI does)

**Comment by bryanjtc** [comment]
Now, I think all menu buttons allow for customizable labels. Bubble menus and Selects are still missing that customization.

**Comment by sjdemartini** [comment]
Alright, all components should now allow you to customize their text labels/content as of the new [v1.1.0 release](https://github.com/sjdemartini/mui-tiptap/tree/v1.1.0), so I've closed this out. I documented some examples of how this is done in the README [here](https://github.com/sjdemartini/mui-tiptap/tree/v1.1.0#localization). Please let me know if I missed anything!
